### ISSUE TITLE
error 500 on /admin/reports/fields/gdpr-fields

### ISSUE THREAD

**Issue by pedro-p** [FreelyGive/gdpr#3]
Just tried out the gdpr_fields submodule. I copied it over to the latest 8.x-1.x-dev codebase of gdpr module from drupal.org. I copied it to the modules subdirectory. 

Drupal core: 8.4.5
php: 7.1.12
user: 1 (admin)

On /admin/reports/fields/gdpr-fields I got error 500:

php_1        | [08-Mar-2018 16:42:52] WARNING: [pool www] child 56 said into stderr: "[08-Mar-2018 16:42:52 UTC] Uncaught PHP Exception Drupal\Component\Plugin\Exception\PluginNotFoundException: "The "entity:" plugin does not exist." at /var/www/html/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php line 52"
php_1        | 172.18.0.8 -  08/Mar/2018:16:42:52 +0000 "GET /index.php"

**Comment by yanniboi** [comment]
Thanks. This is caused because there is a patch that is needed to be applied to ctools. I am uploading it here, but I am also writing up an issue for ctools to be able to fix this better.

**Comment by pedro-p** [comment]
Yes, please open an issue for that on drupal.org and upload the patch there so we can refer to it from composer.json.

**Comment by yanniboi** [comment]
Issue opened:
https://www.drupal.org/project/ctools/issues/2951267

The summary is terrible, but I will correctly describe the issue later when I have more time.

**Comment by yanniboi** [comment]
Apply patch and cache clear should resolve your error.

**Comment by pedro-p** [comment]
Thanks, the patch works for me.
