### ISSUE TITLE
error 500 on /admin/gdpr/summary

### ISSUE THREAD

**Issue by pedro-p** [FreelyGive/gdpr#4]
Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "messenger"." at /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php line 151

user 1
php 7.1.12
drupal core 8.4.5

**Comment by yanniboi** [comment]
Ahh yes sorry, we are using Drupal 8.5.x. Messenger was introduced in that version.

https://www.drupal.org/node/2774931

What version of Drupal core do you want to support?

**Comment by pedro-p** [comment]
Upgraded to core 8.5.0 and the exception is gone.
This is okay this way as 8.4 is not supported any more.
